# Generated by Django 5.2.8 on 2025-11-13 20:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intent_capture', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='intentcapture',
            name='asset_type_guess',
            field=models.CharField(blank=True, help_text='Auto-inferred asset type (building/bridge/road)', max_length=50, null=True),
        ),
        migrations.AddIndex(
            model_name='intentcapture',
            index=models.Index(fields=['user', 'status'], name='intent_capt_user_id_12da22_idx'),
        ),
        migrations.AddIndex(
            model_name='intentcapture',
            index=models.Index(fields=['created_at'], name='intent_capt_created_7ad986_idx'),
        ),
    ]
