# Generated by Django 5.2.8 on 2025-11-13 02:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_initial'),
        ('parametric_generator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyticsrun',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametric_generator.generatedmodel'),
        ),
    ]
