# Generated by Django 5.2.8 on 2026-02-03 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GeneratedIFC",
            fields=[
                (
                    "id",
                    models.AutoField(
                        help_text="Unique IFC record ID",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Name/label for this generated IFC",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "asset_type",
                    models.CharField(
                        choices=[
                            ("building", "Building"),
                            ("residential", "Residential Building"),
                            ("commercial", "Commercial Building"),
                            ("industrial", "Industrial Building"),
                            ("institutional", "Institutional Building"),
                            ("road", "Road"),
                            ("highway", "Highway"),
                            ("bridge", "Bridge"),
                            ("tunnel", "Tunnel"),
                            ("railway", "Railway/Track"),
                            ("parking", "Parking Structure"),
                            ("utility_network", "Utility Network"),
                            ("power_line", "Power Line"),
                            ("pipeline", "Pipeline"),
                            ("water_system", "Water System"),
                            ("drainage", "Drainage System"),
                            ("site", "Site/Lot"),
                            ("landscape", "Landscape"),
                            ("plaza", "Plaza/Court"),
                            ("park", "Park"),
                            ("airport", "Airport"),
                            ("seaport", "Seaport"),
                            ("dam", "Dam"),
                            ("solar_farm", "Solar Farm"),
                            ("wind_farm", "Wind Farm"),
                            ("hvac_system", "HVAC System"),
                            ("electrical_system", "Electrical System"),
                            ("plumbing_system", "Plumbing System"),
                            ("fire_safety", "Fire Safety System"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "ifc_schema_version",
                    models.CharField(
                        choices=[
                            ("ifc2x3", "IFC2x3"),
                            ("ifc4", "IFC4"),
                            ("ifc4x3", "IFC4x3"),
                        ],
                        help_text="IFC schema version used for generation",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("generating", "Generating"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "specifications",
                    models.JSONField(
                        default=dict,
                        help_text="User-provided specifications for this asset",
                    ),
                ),
                (
                    "ifc_file",
                    models.FileField(
                        blank=True,
                        help_text="Generated IFC file (supports S3 or local storage)",
                        null=True,
                        upload_to="ifc_files/%Y/%m/%d/",
                    ),
                ),
                (
                    "file_size",
                    models.BigIntegerField(default=0, help_text="File size in bytes"),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        help_text="Error message if generation failed",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, help_text="When generation completed", null=True
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="Project name", max_length=255)),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Project description", null=True
                    ),
                ),
                (
                    "project_number",
                    models.CharField(
                        help_text="Project number/ID", max_length=100, unique=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("concept", "Concept"),
                            ("schematic", "Schematic"),
                            ("detailed", "Detailed Design"),
                            ("as-built", "As-Built"),
                        ],
                        default="concept",
                        help_text="Project stage",
                        max_length=20,
                    ),
                ),
                (
                    "client_name",
                    models.CharField(
                        blank=True,
                        help_text="Client/Owner name",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("country", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "city_address",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "elevation_above_sea",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Elevation in meters",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "coordinate_reference_system",
                    models.CharField(
                        choices=[
                            ("epsg:4326", "WGS 84 (EPSG:4326)"),
                            ("epsg:3857", "Web Mercator (EPSG:3857)"),
                            ("epsg:3395", "World Mercator (EPSG:3395)"),
                            ("local", "Local Coordinate System"),
                            ("custom", "Custom CRS"),
                        ],
                        default="epsg:4326",
                        help_text="Coordinate Reference System",
                        max_length=50,
                    ),
                ),
                (
                    "true_north",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="True north in degrees",
                        max_digits=5,
                    ),
                ),
                (
                    "project_north_angle",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Project north angle in degrees",
                        max_digits=5,
                    ),
                ),
                (
                    "building_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("residential", "Residential"),
                            ("office", "Office"),
                            ("hospital", "Hospital"),
                            ("educational", "Educational"),
                            ("retail", "Retail"),
                            ("industrial", "Industrial"),
                            ("mixed-use", "Mixed-Use"),
                            ("other", "Other"),
                        ],
                        help_text="Building type/category",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "length_unit",
                    models.CharField(
                        choices=[("mm", "Millimeters"), ("m", "Meters")],
                        default="m",
                        max_length=10,
                    ),
                ),
                (
                    "area_unit",
                    models.CharField(
                        choices=[
                            ("m2", "Square Meters"),
                            ("mm2", "Square Millimeters"),
                        ],
                        default="m2",
                        max_length=10,
                    ),
                ),
                (
                    "volume_unit",
                    models.CharField(
                        choices=[("m3", "Cubic Meters"), ("mm3", "Cubic Millimeters")],
                        default="m3",
                        max_length=10,
                    ),
                ),
                (
                    "angle_unit",
                    models.CharField(
                        choices=[("degree", "Degrees"), ("radian", "Radians")],
                        default="degree",
                        max_length=20,
                    ),
                ),
                (
                    "precision",
                    models.DecimalField(
                        decimal_places=4,
                        default=0.0001,
                        help_text="Geometric precision tolerance",
                        max_digits=5,
                    ),
                ),
                (
                    "ifc_schema_version",
                    models.CharField(
                        choices=[
                            ("ifc2x3", "IFC2x3"),
                            ("ifc4", "IFC4"),
                            ("ifc4x3", "IFC4x3"),
                        ],
                        default="ifc4x3",
                        max_length=20,
                    ),
                ),
                (
                    "climate_zone",
                    models.CharField(
                        blank=True,
                        help_text="Climate zone classification",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "design_temperature",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Design temperature in Celsius",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "design_target",
                    models.CharField(
                        blank=True,
                        help_text="Design performance target or goals",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "materials",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Material specifications: walls, slabs, layers",
                    ),
                ),
                (
                    "authoring_name",
                    models.CharField(
                        blank=True,
                        help_text="Name of project author/creator",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "authoring_company",
                    models.CharField(
                        blank=True,
                        help_text="Company that authored the project",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "approval_status",
                    models.CharField(
                        blank=True,
                        help_text="e.g., Pending, Approved, Rejected",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "revision_id",
                    models.CharField(
                        blank=True,
                        help_text="Current revision identifier",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "change_description",
                    models.TextField(
                        blank=True,
                        help_text="Description of changes in this revision",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
