# Generated by Django 5.2.8 on 2026-02-22 18:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique asset identifier (UUID)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "asset_type",
                    models.CharField(
                        choices=[
                            ("wall", "Wall"),
                            ("beam", "Beam"),
                            ("slab", "Slab"),
                            ("column", "Column"),
                            ("foundation", "Foundation"),
                            ("door", "Door"),
                            ("window", "Window"),
                            ("roof", "Roof"),
                            ("stairs", "Stairs"),
                            ("ramp", "Ramp"),
                            ("shear_wall", "Shear Wall"),
                            ("pipe", "Pipe"),
                            ("duct", "Duct"),
                            ("cable", "Cable"),
                            ("fitting", "Fitting"),
                            ("equipment", "Equipment"),
                            ("sensor", "Sensor"),
                            ("beam_span", "Beam Span"),
                            ("girder", "Girder"),
                            ("pier", "Pier"),
                            ("abutment", "Abutment"),
                            ("bearing", "Bearing"),
                            ("expansion_joint", "Expansion Joint"),
                            ("bridge_railing", "Bridge Railing"),
                            ("bridge_deck", "Bridge Deck Element"),
                            ("pavement", "Pavement"),
                            ("curb", "Curb"),
                            ("marking", "Road Marking"),
                            ("sign", "Road Sign"),
                            ("light", "Street Light"),
                            ("manhole", "Manhole"),
                            ("storm_drain", "Storm Drain"),
                            ("other", "Other"),
                        ],
                        help_text="Type of asset (Wall, Beam, Pipe, etc.)",
                        max_length=50,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name/identifier for this asset (e.g., 'Wall-001', 'Column-A1')",
                        max_length=255,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description of this asset", null=True
                    ),
                ),
                (
                    "properties",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Type-specific properties (material, dimensions, specifications)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["spatial_structure", "asset_type", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="GeneratedIFC",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique IFC record identifier (UUID)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Name/label for this generated IFC",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "asset_type",
                    models.CharField(
                        choices=[
                            ("building", "Building"),
                            ("residential", "Residential Building"),
                            ("commercial", "Commercial Building"),
                            ("industrial", "Industrial Building"),
                            ("institutional", "Institutional Building"),
                            ("road", "Road"),
                            ("highway", "Highway"),
                            ("bridge", "Bridge"),
                            ("tunnel", "Tunnel"),
                            ("railway", "Railway/Track"),
                            ("parking", "Parking Structure"),
                            ("utility_network", "Utility Network"),
                            ("power_line", "Power Line"),
                            ("pipeline", "Pipeline"),
                            ("water_system", "Water System"),
                            ("drainage", "Drainage System"),
                            ("site", "Site/Lot"),
                            ("landscape", "Landscape"),
                            ("plaza", "Plaza/Court"),
                            ("park", "Park"),
                            ("airport", "Airport"),
                            ("seaport", "Seaport"),
                            ("dam", "Dam"),
                            ("solar_farm", "Solar Farm"),
                            ("wind_farm", "Wind Farm"),
                            ("hvac_system", "HVAC System"),
                            ("electrical_system", "Electrical System"),
                            ("plumbing_system", "Plumbing System"),
                            ("fire_safety", "Fire Safety System"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "ifc_schema_version",
                    models.CharField(
                        choices=[
                            ("ifc2x3", "IFC2x3"),
                            ("ifc4", "IFC4"),
                            ("ifc4x3", "IFC4x3"),
                        ],
                        help_text="IFC schema version used for generation",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("generating", "Generating"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "specifications",
                    models.JSONField(
                        default=dict,
                        help_text="User-provided specifications for this asset",
                    ),
                ),
                (
                    "ifc_file",
                    models.FileField(
                        blank=True,
                        help_text="Generated IFC file (supports S3 or local storage)",
                        null=True,
                        upload_to="ifc_files/%Y/%m/%d/",
                    ),
                ),
                (
                    "file_size",
                    models.BigIntegerField(default=0, help_text="File size in bytes"),
                ),
                (
                    "file_format",
                    models.CharField(
                        default="ifc",
                        help_text="File format/extension (ifc, ifcxml, etc.)",
                        max_length=20,
                    ),
                ),
                (
                    "generation_metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Details about generated IFC: element counts, schema info, etc.",
                    ),
                ),
                (
                    "generation_warnings",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Warnings during IFC generation",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        help_text="Error message if generation failed",
                        null=True,
                    ),
                ),
                (
                    "error_details",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Detailed error information including traceback",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, help_text="When generation completed", null=True
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique project identifier (UUID)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(help_text="Project name", max_length=255)),
                (
                    "project_number",
                    models.CharField(
                        help_text="Unique project identifier/number",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Detailed project description", null=True
                    ),
                ),
                (
                    "phase",
                    models.CharField(
                        choices=[
                            ("concept", "Concept"),
                            ("schematic", "Schematic"),
                            ("detailed", "Detailed Design"),
                            ("as-built", "As-Built"),
                        ],
                        default="concept",
                        help_text="Current project design phase",
                        max_length=20,
                    ),
                ),
                (
                    "project_type",
                    models.CharField(
                        choices=[
                            ("BUILDING", "Building"),
                            ("INFRA_ROAD", "Road"),
                            ("INFRA_RAILWAY", "Railway"),
                            ("INFRA_BRIDGE", "Bridge"),
                            ("INFRA_TUNNEL", "Tunnel"),
                            ("INFRA_MARINE", "Marine Facility"),
                            ("INDUSTRIAL_FACTORY", "Factory"),
                            ("INDUSTRIAL_PLANT", "Process Plant"),
                            ("INFRA_DISTRIBUTION", "Distribution System"),
                            ("SITE", "Site / Land Project"),
                            ("OTHER", "Other / Custom"),
                        ],
                        help_text="Primary project type (Building, Road, Bridge, etc.)",
                        max_length=50,
                    ),
                ),
                (
                    "client_name",
                    models.CharField(
                        blank=True,
                        help_text="Name of project client/owner",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "client_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("private", "Private"),
                            ("government", "Government"),
                            ("ngo", "NGO"),
                            ("corporate", "Corporate"),
                        ],
                        help_text="Type of client (Private, Government, NGO, Corporate)",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "project_scale",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("small", "Small"),
                            ("medium", "Medium"),
                            ("large", "Large"),
                        ],
                        help_text="Scale of project (Small, Medium, Large)",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "risk_classification",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("low", "Low Risk"),
                            ("medium", "Medium Risk"),
                            ("high", "High Risk"),
                            ("critical", "Critical Risk"),
                        ],
                        help_text="Risk level classification for project",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "project_address",
                    models.CharField(
                        blank=True,
                        help_text="Principal project address",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "project_start_date",
                    models.DateTimeField(
                        blank=True, help_text="Project initiation date", null=True
                    ),
                ),
                (
                    "construction_start_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Planned or actual construction start date",
                        null=True,
                    ),
                ),
                (
                    "expected_completion_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Expected project completion date",
                        null=True,
                    ),
                ),
                (
                    "approval_status",
                    models.CharField(
                        blank=True,
                        help_text="Approval status (e.g., Pending, Approved, Rejected)",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Project creation timestamp"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Last modification timestamp"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Site",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique site identifier (UUID)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "site_name",
                    models.CharField(
                        help_text="Site name or identifier", max_length=255
                    ),
                ),
                (
                    "project_type",
                    models.CharField(
                        choices=[
                            ("BUILDING", "Building"),
                            ("INFRA_ROAD", "Road"),
                            ("INFRA_RAILWAY", "Railway"),
                            ("INFRA_BRIDGE", "Bridge"),
                            ("INFRA_TUNNEL", "Tunnel"),
                            ("INFRA_MARINE", "Marine Facility"),
                            ("INDUSTRIAL_FACTORY", "Factory"),
                            ("INDUSTRIAL_PLANT", "Process Plant"),
                            ("INFRA_DISTRIBUTION", "Distribution System"),
                            ("SITE", "Site / Land Project"),
                            ("OTHER", "Other / Custom"),
                        ],
                        help_text="Primary site/project type (Building, Road, Bridge, etc.)",
                        max_length=50,
                    ),
                ),
                (
                    "type_metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Type-specific site details. Structure varies by project_type.",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, help_text="Site address", max_length=255, null=True
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="Site latitude in decimal degrees",
                        max_digits=9,
                        null=True,
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="Site longitude in decimal degrees",
                        max_digits=9,
                        null=True,
                    ),
                ),
                (
                    "elevation",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Site elevation above sea level (meters)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "coordinate_reference_system",
                    models.CharField(
                        choices=[
                            ("epsg:4326", "WGS 84 (EPSG:4326)"),
                            ("epsg:3857", "Web Mercator (EPSG:3857)"),
                            ("epsg:3395", "World Mercator (EPSG:3395)"),
                            ("local", "Local Coordinate System"),
                            ("custom", "Custom CRS"),
                        ],
                        default="epsg:4326",
                        help_text="Coordinate Reference System (CRS/EPSG code)",
                        max_length=50,
                    ),
                ),
                (
                    "true_north_angle",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="True north direction in degrees (0-360)",
                        max_digits=5,
                    ),
                ),
                (
                    "project_north_angle",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Project north offset from true north in degrees",
                        max_digits=5,
                    ),
                ),
                (
                    "length_unit",
                    models.CharField(
                        choices=[("mm", "Millimeters"), ("m", "Meters")],
                        default="m",
                        help_text="Unit for length measurements",
                        max_length=10,
                    ),
                ),
                (
                    "area_unit",
                    models.CharField(
                        choices=[
                            ("m2", "Square Meters"),
                            ("mm2", "Square Millimeters"),
                        ],
                        default="m2",
                        help_text="Unit for area measurements",
                        max_length=10,
                    ),
                ),
                (
                    "volume_unit",
                    models.CharField(
                        choices=[("m3", "Cubic Meters"), ("mm3", "Cubic Millimeters")],
                        default="m3",
                        help_text="Unit for volume measurements",
                        max_length=10,
                    ),
                ),
                (
                    "angle_unit",
                    models.CharField(
                        choices=[("degree", "Degrees"), ("radian", "Radians")],
                        default="degree",
                        help_text="Unit for angle measurements",
                        max_length=20,
                    ),
                ),
                (
                    "precision",
                    models.DecimalField(
                        decimal_places=4,
                        default=0.0001,
                        help_text="Geometric precision tolerance",
                        max_digits=5,
                    ),
                ),
                (
                    "ifc_schema_version",
                    models.CharField(
                        choices=[
                            ("ifc2x3", "IFC2x3"),
                            ("ifc4", "IFC4"),
                            ("ifc4x3", "IFC4x3"),
                        ],
                        default="ifc4x3",
                        help_text="IFC schema version for generation",
                        max_length=20,
                    ),
                ),
                (
                    "climate_zone",
                    models.CharField(
                        blank=True,
                        help_text="Climate zone classification (e.g., temperate, tropical, arctic)",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "design_temperature",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Design temperature in Celsius",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "material_system",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Material system and specifications",
                    ),
                ),
                (
                    "regulatory_requirements",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Applicable codes, standards, and regulatory requirements",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Site creation timestamp"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Last modification timestamp"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SpatialStructure",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique spatial structure identifier (UUID)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "spatial_type",
                    models.CharField(
                        choices=[
                            ("ifc_building", "IfcBuilding"),
                            ("ifc_building_storey", "IfcBuildingStorey"),
                            ("ifc_space", "IfcSpace"),
                            ("ifc_zone", "IfcZone"),
                            ("ifc_bridge", "IfcBridge"),
                            ("ifc_bridge_part", "IfcBridgePart"),
                            ("ifc_structural_member", "IfcStructuralMember"),
                            ("ifc_road", "IfcRoad"),
                            ("ifc_road_part", "IfcRoadPart"),
                            ("ifc_alignment", "IfcAlignment"),
                            ("ifc_site", "IfcSite"),
                        ],
                        help_text="Type of spatial element (Building, Storey, Bridge, Deck, Road, Segment, etc.)",
                        max_length=50,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name/identifier for this spatial structure (e.g., 'Ground Floor', 'Main Span')",
                        max_length=255,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description of this spatial structure",
                        null=True,
                    ),
                ),
                (
                    "level",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Depth level in hierarchy (0=root, 1=first children, etc.)",
                    ),
                ),
                (
                    "order_in_parent",
                    models.PositiveIntegerField(
                        default=0, help_text="Order/sequence within parent structure"
                    ),
                ),
                (
                    "properties",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Type-specific properties (dimensions, materials, specifications)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["level", "order_in_parent", "created_at"],
            },
        ),
    ]
