# Generated by Django 5.2.8 on 2026-02-03 00:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("parametric_generator", "0001_initial"),
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="organization",
            field=models.ForeignKey(
                help_text="Organization that owns this project",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="projects",
                to="users.organization",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="user",
            field=models.ForeignKey(
                help_text="User who created the project",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_projects",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="generatedifc",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="generated_ifcs",
                to="parametric_generator.project",
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["user", "created_at"], name="parametric__user_id_a75637_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["project_number"], name="parametric__project_ef5204_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(fields=["status"], name="parametric__status_4df31e_idx"),
        ),
        migrations.AddIndex(
            model_name="generatedifc",
            index=models.Index(
                fields=["project", "status"], name="parametric__project_b5fedc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="generatedifc",
            index=models.Index(
                fields=["asset_type"], name="parametric__asset_t_25bd2e_idx"
            ),
        ),
    ]
