# Generated by Django 5.2.8 on 2026-02-22 18:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("parametric_generator", "0001_initial"),
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="organization",
            field=models.ForeignKey(
                help_text="Organization that owns this project",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="projects",
                to="users.organization",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="user",
            field=models.ForeignKey(
                help_text="User who created the project",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_projects",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="generatedifc",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="generated_ifcs",
                to="parametric_generator.project",
            ),
        ),
        migrations.AddField(
            model_name="site",
            name="project",
            field=models.ForeignKey(
                help_text="Project this site belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sites",
                to="parametric_generator.project",
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="site",
            field=models.ForeignKey(
                help_text="Site for quick filtering and context",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assets",
                to="parametric_generator.site",
            ),
        ),
        migrations.AddField(
            model_name="spatialstructure",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                help_text="Parent spatial structure in hierarchy",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="parametric_generator.spatialstructure",
            ),
        ),
        migrations.AddField(
            model_name="spatialstructure",
            name="site",
            field=models.ForeignKey(
                help_text="Site this spatial structure belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="spatial_structures",
                to="parametric_generator.site",
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="spatial_structure",
            field=models.ForeignKey(
                help_text="Spatial structure this asset belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assets",
                to="parametric_generator.spatialstructure",
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["user", "created_at"], name="parametric__user_id_a75637_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["project_number"], name="parametric__project_ef5204_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(fields=["phase"], name="parametric__phase_e1be5c_idx"),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["project_type"], name="parametric__project_f830af_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="generatedifc",
            index=models.Index(
                fields=["project", "status"], name="parametric__project_b5fedc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="generatedifc",
            index=models.Index(
                fields=["asset_type"], name="parametric__asset_t_25bd2e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="site",
            index=models.Index(
                fields=["project", "created_at"], name="parametric__project_b2be46_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="site",
            index=models.Index(
                fields=["coordinate_reference_system"],
                name="parametric__coordin_192c9b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="spatialstructure",
            index=models.Index(
                fields=["site", "spatial_type"], name="parametric__site_id_5d8ef9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="spatialstructure",
            index=models.Index(
                fields=["parent", "level"], name="parametric__parent__bcf6e5_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="spatialstructure",
            unique_together={("site", "name")},
        ),
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(
                fields=["site", "asset_type"], name="parametric__site_id_005f9c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(
                fields=["spatial_structure", "asset_type"],
                name="parametric__spatial_dd6814_idx",
            ),
        ),
    ]
