# Generated by Django 5.2.8 on 2026-02-04 01:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parametric_generator", "0002_initial"),
        ("users", "0002_alter_requestsubmission_request_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="building_type",
        ),
        migrations.RemoveField(
            model_name="project",
            name="city_address",
        ),
        migrations.RemoveField(
            model_name="project",
            name="client_name",
        ),
        migrations.RemoveField(
            model_name="project",
            name="elevation_above_sea",
        ),
        migrations.RemoveField(
            model_name="project",
            name="materials",
        ),
        migrations.RemoveField(
            model_name="project",
            name="true_north",
        ),
        migrations.AddField(
            model_name="project",
            name="address",
            field=models.CharField(
                blank=True,
                help_text="Street address or project site address",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="city",
            field=models.CharField(
                blank=True, help_text="City or locality", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="elevation",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Site elevation above sea level (meters)",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="material_system",
            field=models.JSONField(
                blank=True, default=dict, help_text="Material system and specifications"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="project_type",
            field=models.CharField(
                choices=[
                    ("IFC_BUILDING", "Building"),
                    ("IFC_ROAD", "Road"),
                    ("IFC_RAILWAY", "Railway"),
                    ("IFC_BRIDGE", "Bridge"),
                    ("IFC_TUNNEL", "Tunnel"),
                    ("IFC_MARINE_FACILITY", "Marine Facility"),
                    ("IFC_FACTORY", "Factory"),
                    ("IFC_PROCESS_PLANT", "Process Plant"),
                    ("IFC_DISTRIBUTION_SYSTEM", "Distribution System"),
                    ("IFC_SITE", "Site / Land Project"),
                    ("OTHER", "Other / Custom"),
                ],
                default="IFC_BUILDING",
                help_text="Primary project type (Building, Road, Bridge, etc.)",
                max_length=50,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="project",
            name="region",
            field=models.CharField(
                blank=True, help_text="State/Province/Region", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="regulatory_requirements",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Applicable codes, standards, and regulatory requirements",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="target_completion_date",
            field=models.DateTimeField(
                blank=True, help_text="Target project completion date", null=True
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="true_north_angle",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="True north direction in degrees (0-360)",
                max_digits=5,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="type_metadata",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Type-specific project details. Structure varies by project_type.",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="angle_unit",
            field=models.CharField(
                choices=[("degree", "Degrees"), ("radian", "Radians")],
                default="degree",
                help_text="Unit for angle measurements",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="approval_status",
            field=models.CharField(
                blank=True,
                help_text="Approval status (e.g., Pending, Approved, Rejected)",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="area_unit",
            field=models.CharField(
                choices=[("m2", "Square Meters"), ("mm2", "Square Millimeters")],
                default="m2",
                help_text="Unit for area measurements",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="authoring_company",
            field=models.CharField(
                blank=True,
                help_text="Company that authored the design",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="authoring_name",
            field=models.CharField(
                blank=True,
                help_text="Name of project author/designer",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="change_description",
            field=models.TextField(
                blank=True,
                help_text="Description of changes in current revision",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="climate_zone",
            field=models.CharField(
                blank=True,
                help_text="Climate zone classification (e.g., temperate, tropical, arctic)",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="coordinate_reference_system",
            field=models.CharField(
                choices=[
                    ("epsg:4326", "WGS 84 (EPSG:4326)"),
                    ("epsg:3857", "Web Mercator (EPSG:3857)"),
                    ("epsg:3395", "World Mercator (EPSG:3395)"),
                    ("local", "Local Coordinate System"),
                    ("custom", "Custom CRS"),
                ],
                default="epsg:4326",
                help_text="Coordinate Reference System (CRS/EPSG code)",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="country",
            field=models.CharField(
                blank=True,
                help_text="Country where project is located",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Project creation timestamp"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="description",
            field=models.TextField(
                blank=True, help_text="Detailed project description", null=True
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="design_target",
            field=models.TextField(
                blank=True, help_text="Design goals and performance targets", null=True
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="ifc_schema_version",
            field=models.CharField(
                choices=[("ifc2x3", "IFC2x3"), ("ifc4", "IFC4"), ("ifc4x3", "IFC4x3")],
                default="ifc4x3",
                help_text="IFC schema version for generation",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Site latitude in decimal degrees",
                max_digits=9,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="length_unit",
            field=models.CharField(
                choices=[("mm", "Millimeters"), ("m", "Meters")],
                default="m",
                help_text="Unit for length measurements",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Site longitude in decimal degrees",
                max_digits=9,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="project_north_angle",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Project north offset from true north in degrees",
                max_digits=5,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="project_number",
            field=models.CharField(
                help_text="Unique project identifier/number",
                max_length=100,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="status",
            field=models.CharField(
                choices=[
                    ("concept", "Concept"),
                    ("schematic", "Schematic"),
                    ("detailed", "Detailed Design"),
                    ("as-built", "As-Built"),
                ],
                default="concept",
                help_text="Current project stage/phase",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, help_text="Last modification timestamp"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="volume_unit",
            field=models.CharField(
                choices=[("m3", "Cubic Meters"), ("mm3", "Cubic Millimeters")],
                default="m3",
                help_text="Unit for volume measurements",
                max_length=10,
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["project_type"], name="parametric__project_f830af_idx"
            ),
        ),
    ]
