# Generated by Django 5.2.8 on 2026-02-04 01:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parametric_generator", "0003_remove_project_building_type_and_more"),
        ("users", "0002_alter_requestsubmission_request_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="project",
            name="parametric__status_4df31e_idx",
        ),
        migrations.RemoveField(
            model_name="project",
            name="status",
        ),
        migrations.AddField(
            model_name="project",
            name="phase",
            field=models.CharField(
                choices=[
                    ("concept", "Concept"),
                    ("schematic", "Schematic"),
                    ("detailed", "Detailed Design"),
                    ("as-built", "As-Built"),
                ],
                default="concept",
                help_text="Current project design phase",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(fields=["phase"], name="parametric__phase_e1be5c_idx"),
        ),
    ]
