# Generated by Django 5.2.8 on 2026-02-08 01:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "parametric_generator",
            "0004_remove_project_parametric__status_4df31e_idx_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="address",
        ),
        migrations.RemoveField(
            model_name="project",
            name="angle_unit",
        ),
        migrations.RemoveField(
            model_name="project",
            name="area_unit",
        ),
        migrations.RemoveField(
            model_name="project",
            name="authoring_company",
        ),
        migrations.RemoveField(
            model_name="project",
            name="authoring_name",
        ),
        migrations.RemoveField(
            model_name="project",
            name="change_description",
        ),
        migrations.RemoveField(
            model_name="project",
            name="city",
        ),
        migrations.RemoveField(
            model_name="project",
            name="climate_zone",
        ),
        migrations.RemoveField(
            model_name="project",
            name="coordinate_reference_system",
        ),
        migrations.RemoveField(
            model_name="project",
            name="country",
        ),
        migrations.RemoveField(
            model_name="project",
            name="design_target",
        ),
        migrations.RemoveField(
            model_name="project",
            name="design_temperature",
        ),
        migrations.RemoveField(
            model_name="project",
            name="elevation",
        ),
        migrations.RemoveField(
            model_name="project",
            name="ifc_schema_version",
        ),
        migrations.RemoveField(
            model_name="project",
            name="latitude",
        ),
        migrations.RemoveField(
            model_name="project",
            name="length_unit",
        ),
        migrations.RemoveField(
            model_name="project",
            name="longitude",
        ),
        migrations.RemoveField(
            model_name="project",
            name="material_system",
        ),
        migrations.RemoveField(
            model_name="project",
            name="precision",
        ),
        migrations.RemoveField(
            model_name="project",
            name="project_north_angle",
        ),
        migrations.RemoveField(
            model_name="project",
            name="region",
        ),
        migrations.RemoveField(
            model_name="project",
            name="regulatory_requirements",
        ),
        migrations.RemoveField(
            model_name="project",
            name="revision_id",
        ),
        migrations.RemoveField(
            model_name="project",
            name="target_completion_date",
        ),
        migrations.RemoveField(
            model_name="project",
            name="true_north_angle",
        ),
        migrations.RemoveField(
            model_name="project",
            name="type_metadata",
        ),
        migrations.RemoveField(
            model_name="project",
            name="volume_unit",
        ),
        migrations.AddField(
            model_name="project",
            name="client_name",
            field=models.CharField(
                blank=True,
                help_text="Name of project client/owner",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="client_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("private", "Private"),
                    ("government", "Government"),
                    ("ngo", "NGO"),
                    ("corporate", "Corporate"),
                ],
                help_text="Type of client (Private, Government, NGO, Corporate)",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="construction_start_date",
            field=models.DateTimeField(
                blank=True,
                help_text="Planned or actual construction start date",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="expected_completion_date",
            field=models.DateTimeField(
                blank=True, help_text="Expected project completion date", null=True
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="project_address",
            field=models.CharField(
                blank=True,
                help_text="Principal project address",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="project_scale",
            field=models.CharField(
                blank=True,
                choices=[("small", "Small"), ("medium", "Medium"), ("large", "Large")],
                help_text="Scale of project (Small, Medium, Large)",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="project_start_date",
            field=models.DateTimeField(
                blank=True, help_text="Project initiation date", null=True
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="risk_classification",
            field=models.CharField(
                blank=True,
                choices=[
                    ("low", "Low Risk"),
                    ("medium", "Medium Risk"),
                    ("high", "High Risk"),
                    ("critical", "Critical Risk"),
                ],
                help_text="Risk level classification for project",
                max_length=20,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="Site",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "site_name",
                    models.CharField(
                        help_text="Site name or identifier", max_length=255
                    ),
                ),
                (
                    "project_type",
                    models.CharField(
                        choices=[
                            ("IFC_BUILDING", "Building"),
                            ("IFC_ROAD", "Road"),
                            ("IFC_RAILWAY", "Railway"),
                            ("IFC_BRIDGE", "Bridge"),
                            ("IFC_TUNNEL", "Tunnel"),
                            ("IFC_MARINE_FACILITY", "Marine Facility"),
                            ("IFC_FACTORY", "Factory"),
                            ("IFC_PROCESS_PLANT", "Process Plant"),
                            ("IFC_DISTRIBUTION_SYSTEM", "Distribution System"),
                            ("IFC_SITE", "Site / Land Project"),
                            ("OTHER", "Other / Custom"),
                        ],
                        help_text="Primary site/project type (Building, Road, Bridge, etc.)",
                        max_length=50,
                    ),
                ),
                (
                    "type_metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Type-specific site details. Structure varies by project_type.",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, help_text="Site address", max_length=255, null=True
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="Site latitude in decimal degrees",
                        max_digits=9,
                        null=True,
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="Site longitude in decimal degrees",
                        max_digits=9,
                        null=True,
                    ),
                ),
                (
                    "elevation",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Site elevation above sea level (meters)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "coordinate_reference_system",
                    models.CharField(
                        choices=[
                            ("epsg:4326", "WGS 84 (EPSG:4326)"),
                            ("epsg:3857", "Web Mercator (EPSG:3857)"),
                            ("epsg:3395", "World Mercator (EPSG:3395)"),
                            ("local", "Local Coordinate System"),
                            ("custom", "Custom CRS"),
                        ],
                        default="epsg:4326",
                        help_text="Coordinate Reference System (CRS/EPSG code)",
                        max_length=50,
                    ),
                ),
                (
                    "true_north_angle",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="True north direction in degrees (0-360)",
                        max_digits=5,
                    ),
                ),
                (
                    "project_north_angle",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Project north offset from true north in degrees",
                        max_digits=5,
                    ),
                ),
                (
                    "length_unit",
                    models.CharField(
                        choices=[("mm", "Millimeters"), ("m", "Meters")],
                        default="m",
                        help_text="Unit for length measurements",
                        max_length=10,
                    ),
                ),
                (
                    "area_unit",
                    models.CharField(
                        choices=[
                            ("m2", "Square Meters"),
                            ("mm2", "Square Millimeters"),
                        ],
                        default="m2",
                        help_text="Unit for area measurements",
                        max_length=10,
                    ),
                ),
                (
                    "volume_unit",
                    models.CharField(
                        choices=[("m3", "Cubic Meters"), ("mm3", "Cubic Millimeters")],
                        default="m3",
                        help_text="Unit for volume measurements",
                        max_length=10,
                    ),
                ),
                (
                    "angle_unit",
                    models.CharField(
                        choices=[("degree", "Degrees"), ("radian", "Radians")],
                        default="degree",
                        help_text="Unit for angle measurements",
                        max_length=20,
                    ),
                ),
                (
                    "precision",
                    models.DecimalField(
                        decimal_places=4,
                        default=0.0001,
                        help_text="Geometric precision tolerance",
                        max_digits=5,
                    ),
                ),
                (
                    "ifc_schema_version",
                    models.CharField(
                        choices=[
                            ("ifc2x3", "IFC2x3"),
                            ("ifc4", "IFC4"),
                            ("ifc4x3", "IFC4x3"),
                        ],
                        default="ifc4x3",
                        help_text="IFC schema version for generation",
                        max_length=20,
                    ),
                ),
                (
                    "climate_zone",
                    models.CharField(
                        blank=True,
                        help_text="Climate zone classification (e.g., temperate, tropical, arctic)",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "design_temperature",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Design temperature in Celsius",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "material_system",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Material system and specifications",
                    ),
                ),
                (
                    "regulatory_requirements",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Applicable codes, standards, and regulatory requirements",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Site creation timestamp"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Last modification timestamp"
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        help_text="Project this site belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sites",
                        to="parametric_generator.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["project", "created_at"],
                        name="parametric__project_b2be46_idx",
                    ),
                    models.Index(
                        fields=["coordinate_reference_system"],
                        name="parametric__coordin_192c9b_idx",
                    ),
                ],
            },
        ),
    ]
