# Generated by Django 5.2.8 on 2026-02-15 11:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "parametric_generator",
            "0005_remove_project_address_remove_project_angle_unit_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="generatedifc",
            name="error_details",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Detailed error information including traceback",
            ),
        ),
        migrations.AddField(
            model_name="generatedifc",
            name="file_format",
            field=models.CharField(
                default="ifc",
                help_text="File format/extension (ifc, ifcxml, etc.)",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="generatedifc",
            name="generation_metadata",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Details about generated IFC: element counts, schema info, etc.",
            ),
        ),
        migrations.AddField(
            model_name="generatedifc",
            name="generation_warnings",
            field=models.JSONField(
                blank=True, default=list, help_text="Warnings during IFC generation"
            ),
        ),
        migrations.AlterField(
            model_name="generatedifc",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                help_text="Unique IFC record identifier (UUID)",
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                help_text="Unique project identifier (UUID)",
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="project_type",
            field=models.CharField(
                choices=[
                    ("BUILDING", "Building"),
                    ("INFRA_ROAD", "Road"),
                    ("INFRA_RAILWAY", "Railway"),
                    ("INFRA_BRIDGE", "Bridge"),
                    ("INFRA_TUNNEL", "Tunnel"),
                    ("INFRA_MARINE", "Marine Facility"),
                    ("INDUSTRIAL_FACTORY", "Factory"),
                    ("INDUSTRIAL_PLANT", "Process Plant"),
                    ("INFRA_DISTRIBUTION", "Distribution System"),
                    ("SITE", "Site / Land Project"),
                    ("OTHER", "Other / Custom"),
                ],
                help_text="Primary project type (Building, Road, Bridge, etc.)",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="site",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                help_text="Unique site identifier (UUID)",
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="site",
            name="project_type",
            field=models.CharField(
                choices=[
                    ("BUILDING", "Building"),
                    ("INFRA_ROAD", "Road"),
                    ("INFRA_RAILWAY", "Railway"),
                    ("INFRA_BRIDGE", "Bridge"),
                    ("INFRA_TUNNEL", "Tunnel"),
                    ("INFRA_MARINE", "Marine Facility"),
                    ("INDUSTRIAL_FACTORY", "Factory"),
                    ("INDUSTRIAL_PLANT", "Process Plant"),
                    ("INFRA_DISTRIBUTION", "Distribution System"),
                    ("SITE", "Site / Land Project"),
                    ("OTHER", "Other / Custom"),
                ],
                help_text="Primary site/project type (Building, Road, Bridge, etc.)",
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="SpatialStructure",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique spatial structure identifier (UUID)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "spatial_type",
                    models.CharField(
                        choices=[
                            ("ifc_building", "IfcBuilding"),
                            ("ifc_building_storey", "IfcBuildingStorey"),
                            ("ifc_space", "IfcSpace"),
                            ("ifc_zone", "IfcZone"),
                            ("ifc_bridge", "IfcBridge"),
                            ("ifc_bridge_part", "IfcBridgePart"),
                            ("ifc_structural_member", "IfcStructuralMember"),
                            ("ifc_road", "IfcRoad"),
                            ("ifc_road_part", "IfcRoadPart"),
                            ("ifc_alignment", "IfcAlignment"),
                            ("ifc_site", "IfcSite"),
                        ],
                        help_text="Type of spatial element (Building, Storey, Bridge, Deck, Road, Segment, etc.)",
                        max_length=50,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name/identifier for this spatial structure (e.g., 'Ground Floor', 'Main Span')",
                        max_length=255,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description of this spatial structure",
                        null=True,
                    ),
                ),
                (
                    "level",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Depth level in hierarchy (0=root, 1=first children, etc.)",
                    ),
                ),
                (
                    "order_in_parent",
                    models.PositiveIntegerField(
                        default=0, help_text="Order/sequence within parent structure"
                    ),
                ),
                (
                    "properties",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Type-specific properties (dimensions, materials, specifications)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Parent spatial structure in hierarchy",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="parametric_generator.spatialstructure",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        help_text="Site this spatial structure belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="spatial_structures",
                        to="parametric_generator.site",
                    ),
                ),
            ],
            options={
                "ordering": ["level", "order_in_parent", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique asset identifier (UUID)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "asset_type",
                    models.CharField(
                        choices=[
                            ("wall", "Wall"),
                            ("beam", "Beam"),
                            ("slab", "Slab"),
                            ("column", "Column"),
                            ("foundation", "Foundation"),
                            ("door", "Door"),
                            ("window", "Window"),
                            ("roof", "Roof"),
                            ("stairs", "Stairs"),
                            ("ramp", "Ramp"),
                            ("shear_wall", "Shear Wall"),
                            ("pipe", "Pipe"),
                            ("duct", "Duct"),
                            ("cable", "Cable"),
                            ("fitting", "Fitting"),
                            ("equipment", "Equipment"),
                            ("sensor", "Sensor"),
                            ("beam_span", "Beam Span"),
                            ("girder", "Girder"),
                            ("pier", "Pier"),
                            ("abutment", "Abutment"),
                            ("bearing", "Bearing"),
                            ("expansion_joint", "Expansion Joint"),
                            ("bridge_railing", "Bridge Railing"),
                            ("bridge_deck", "Bridge Deck Element"),
                            ("pavement", "Pavement"),
                            ("curb", "Curb"),
                            ("marking", "Road Marking"),
                            ("sign", "Road Sign"),
                            ("light", "Street Light"),
                            ("manhole", "Manhole"),
                            ("storm_drain", "Storm Drain"),
                            ("other", "Other"),
                        ],
                        help_text="Type of asset (Wall, Beam, Pipe, etc.)",
                        max_length=50,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name/identifier for this asset (e.g., 'Wall-001', 'Column-A1')",
                        max_length=255,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description of this asset", null=True
                    ),
                ),
                (
                    "properties",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Type-specific properties (material, dimensions, specifications)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "site",
                    models.ForeignKey(
                        help_text="Site for quick filtering and context",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assets",
                        to="parametric_generator.site",
                    ),
                ),
                (
                    "spatial_structure",
                    models.ForeignKey(
                        help_text="Spatial structure this asset belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assets",
                        to="parametric_generator.spatialstructure",
                    ),
                ),
            ],
            options={
                "ordering": ["spatial_structure", "asset_type", "created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="spatialstructure",
            index=models.Index(
                fields=["site", "spatial_type"], name="parametric__site_id_5d8ef9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="spatialstructure",
            index=models.Index(
                fields=["parent", "level"], name="parametric__parent__bcf6e5_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="spatialstructure",
            unique_together={("site", "name")},
        ),
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(
                fields=["site", "asset_type"], name="parametric__site_id_005f9c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(
                fields=["spatial_structure", "asset_type"],
                name="parametric__spatial_dd6814_idx",
            ),
        ),
    ]
