# Generated by Django 5.2.8 on 2026-01-24 01:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Organization name", max_length=255),
                ),
                (
                    "slug",
                    models.SlugField(help_text="URL-friendly identifier", unique=True),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "contact_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "contact_phone",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("website", models.URLField(blank=True, null=True)),
                ("country", models.CharField(blank=True, max_length=100, null=True)),
                ("state", models.CharField(blank=True, max_length=100, null=True)),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                ("address", models.TextField(blank=True, null=True)),
                ("postal_code", models.CharField(blank=True, max_length=20, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "owner",
                    models.ForeignKey(
                        help_text="Organization owner",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owned_organizations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrganizationMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("owner", "Owner"),
                            ("admin", "Administrator"),
                            ("manager", "Manager"),
                            ("member", "Member"),
                            ("viewer", "Viewer"),
                        ],
                        default="member",
                        max_length=20,
                    ),
                ),
                ("can_edit_projects", models.BooleanField(default=False)),
                ("can_delete_projects", models.BooleanField(default=False)),
                ("can_manage_team", models.BooleanField(default=False)),
                ("can_manage_settings", models.BooleanField(default=False)),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "invited_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invitations_sent",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organization_members",
                        to="users.organization",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organization_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RequestSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "request_type",
                    models.CharField(
                        choices=[
                            ("request_demo", "Request a Demo"),
                            ("general_enquiries", "General Enquiries"),
                            ("compliance_validation", "Compliance Validation"),
                            ("other", "Other"),
                        ],
                        help_text="Type of request",
                        max_length=25,
                    ),
                ),
                ("firstname", models.CharField(help_text="First name", max_length=100)),
                ("lastname", models.CharField(help_text="Last name", max_length=100)),
                ("email", models.EmailField(help_text="Email address", max_length=254)),
                (
                    "company_name",
                    models.CharField(help_text="Company name", max_length=200),
                ),
                ("company_address", models.TextField(help_text="Company address")),
                ("country", models.CharField(help_text="Country", max_length=100)),
                (
                    "sector",
                    models.CharField(help_text="Industry sector", max_length=100),
                ),
                ("job_title", models.CharField(help_text="Job title", max_length=150)),
                (
                    "phone_number",
                    models.CharField(help_text="Phone number", max_length=20),
                ),
                (
                    "additional_details",
                    models.TextField(
                        blank=True, help_text="Additional details or message", null=True
                    ),
                ),
                (
                    "consent_marketing",
                    models.BooleanField(
                        default=False,
                        help_text="Consent to receive marketing communications",
                    ),
                ),
                (
                    "consent_privacy",
                    models.BooleanField(
                        default=False, help_text="Consent to privacy policy"
                    ),
                ),
                (
                    "email_sent",
                    models.BooleanField(
                        default=False,
                        help_text="Flag indicating if notification email was sent successfully",
                    ),
                ),
                (
                    "admin_response",
                    models.TextField(
                        blank=True,
                        help_text="Admin's response message to the user",
                        null=True,
                    ),
                ),
                (
                    "admin_response_sent",
                    models.BooleanField(
                        default=False,
                        help_text="Flag indicating if admin response was sent to user",
                    ),
                ),
                (
                    "onboarding_email_sent",
                    models.BooleanField(
                        default=False,
                        help_text="Flag indicating if onboarding email was sent to user",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "onboarded_user",
                    models.OneToOneField(
                        blank=True,
                        help_text="User account created from this request",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="organization",
            index=models.Index(
                fields=["owner", "is_active"], name="auth_org_owner_active_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="organization",
            index=models.Index(fields=["slug"], name="auth_org_slug_idx"),
        ),
        migrations.AddIndex(
            model_name="organizationmember",
            index=models.Index(
                fields=["organization", "user", "is_active"],
                name="auth_org_user_active_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="organizationmember",
            unique_together={("organization", "user")},
        ),
        migrations.AddIndex(
            model_name="requestsubmission",
            index=models.Index(
                fields=["request_type", "created_at"],
                name="users_reque_request_61a49a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="requestsubmission",
            index=models.Index(fields=["email"], name="users_reque_email_34aa82_idx"),
        ),
    ]
