# Generated by Django 5.2.8 on 2026-02-04 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="requestsubmission",
            name="request_type",
            field=models.CharField(
                choices=[
                    ("request_demo", "Demo Request"),
                    ("general_enquiries", "General Enquiries"),
                    ("run_model_analysis", "Run Model Analysis"),
                    ("compliance_validation", "Compliance Validation"),
                    ("other", "Other"),
                ],
                help_text="Type of request",
                max_length=25,
            ),
        ),
    ]
