# Generated by Django 5.2.8 on 2026-01-24 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="requestsubmission",
            name="company_position",
            field=models.CharField(
                blank=True,
                help_text="Position/role in the company (e.g., Manager, Director, Executive)",
                max_length=150,
                null=True,
            ),
        ),
    ]
