# Generated by Django 5.2.8 on 2026-02-08 01:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_requestsubmission_request_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="PasswordResetToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        help_text="Unique reset token", max_length=255, unique=True
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Token creation timestamp"
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(help_text="Token expiry timestamp"),
                ),
                (
                    "is_used",
                    models.BooleanField(
                        default=False,
                        help_text="Whether token has been used for password reset",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User requesting password reset",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="password_reset_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["token"], name="users_passw_token_b56ca3_idx"),
                    models.Index(
                        fields=["user", "is_used"],
                        name="users_passw_user_id_5ee9a9_idx",
                    ),
                    models.Index(
                        fields=["expires_at"], name="users_passw_expires_853bc2_idx"
                    ),
                ],
            },
        ),
    ]
