# Generated by Django 5.2.8 on 2026-02-10 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_passwordresettoken"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="company",
            field=models.CharField(
                blank=True, help_text="Company name", max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="job_title",
            field=models.CharField(
                blank=True, help_text="Job title/position", max_length=150, null=True
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="location",
            field=models.CharField(
                blank=True,
                help_text="User location (city/country)",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                blank=True, help_text="User phone number", max_length=20, null=True
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                help_text="User profile picture",
                null=True,
                upload_to="profile_pictures/%Y/%m/%d/",
            ),
        ),
    ]
