# Generated by Django 5.2.8 on 2025-11-14 10:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametric_generator', '0002_generatedmodel_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generatedmodel',
            name='scenario_version',
        ),
        migrations.AlterField(
            model_name='generatedmodel',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='generated_models', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
