# Generated by Django 5.2.8 on 2026-02-03 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AnalyticsRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "analytics_type",
                    models.CharField(
                        choices=[
                            ("qto", "Quantity Takeoff"),
                            ("cost_estimate", "Cost Estimation"),
                            ("schedule", "Schedule"),
                            ("anomaly_detection", "Anomaly Detection"),
                        ],
                        max_length=20,
                    ),
                ),
                ("results", models.JSONField(default=dict)),
                (
                    "report_file",
                    models.FileField(
                        blank=True, null=True, upload_to="analytics_reports/%Y/%m/%d/"
                    ),
                ),
                ("has_anomalies", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
