# Generated by Django 5.2.8 on 2026-02-03 00:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("analytics", "0001_initial"),
        ("parametric_generator", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="analyticsrun",
            name="generated_ifc",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="analytics_runs",
                to="parametric_generator.generatedifc",
            ),
        ),
    ]
