# Generated by hand on 2026-04-15

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("analytics", "0002_initial"),
        ("parametric_generator", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="IFCAnalysisFile",
            fields=[
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[("generated", "Generated on platform"), ("uploaded", "Uploaded by user")],
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("uploaded_ifc", models.FileField(blank=True, null=True, upload_to="analytics_uploads/%Y/%m/%d/")),
                ("file_url", models.URLField(blank=True)),
                ("file_size_bytes", models.BigIntegerField(blank=True, null=True)),
                ("ifc_schema", models.CharField(blank=True, max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "generated_ifc",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analysis_files",
                        to="parametric_generator.generatedifc",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ifc_analysis_files",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="AnalysisSession",
            fields=[
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=255)),
                ("analysis_types", models.JSONField(blank=True, default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("done", "Done"),
                            ("partial", "Partial"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("celery_group_id", models.CharField(blank=True, default="", max_length=255)),
                ("report_pdf_path", models.TextField(blank=True, default="")),
                ("report_json_path", models.TextField(blank=True, default="")),
                ("report_generated_at", models.DateTimeField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "ifc_source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="analytics.ifcanalysisfile",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analysis_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="AnalysisResult",
            fields=[
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                (
                    "analysis_type",
                    models.CharField(
                        choices=[
                            ("qto", "Quantity Takeoff"),
                            ("cost_estimate", "Cost Estimation"),
                            ("schedule", "Schedule"),
                            ("anomaly_detection", "Anomaly Detection"),
                            ("geometry_stats", "Geometry Stats"),
                            ("entity_counts", "Entity Counts"),
                            ("clash_detection", "Clash Detection"),
                            ("code_compliance", "Code Compliance"),
                            ("energy_usage", "Energy Usage"),
                            ("carbon_estimate", "Carbon Estimate"),
                            ("structural_checks", "Structural Checks"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("done", "Done"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("info", "Info"),
                            ("warning", "Warning"),
                            ("error", "Error"),
                            ("critical", "Critical"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("result_data", models.JSONField(blank=True, null=True)),
                ("summary", models.TextField(blank=True)),
                ("issue_count", models.IntegerField(default=0)),
                ("duration_ms", models.IntegerField(blank=True, null=True)),
                ("error_detail", models.JSONField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "ifc_source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="analytics.ifcanalysisfile",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="analytics.analysissession",
                    ),
                ),
            ],
            options={"ordering": ["analysis_type", "id"]},
        ),
        migrations.AddIndex(
            model_name="ifcanalysisfile",
            index=models.Index(fields=["owner", "source_type"], name="analytics_if_owner_09020f_idx"),
        ),
        migrations.AddIndex(
            model_name="ifcanalysisfile",
            index=models.Index(fields=["created_at"], name="analytics_if_created_652520_i"),
        ),
        migrations.AddIndex(
            model_name="analysissession",
            index=models.Index(fields=["owner", "status", "created_at"], name="analytics_an_owner_ba5614_idx"),
        ),
        migrations.AddIndex(
            model_name="analysissession",
            index=models.Index(fields=["ifc_source", "created_at"], name="analytics_an_ifc_so_d710d0_idx"),
        ),
        migrations.AddIndex(
            model_name="analysissession",
            index=models.Index(fields=["celery_group_id"], name="analytics_an_celery_07f297_idx"),
        ),
        migrations.AddConstraint(
            model_name="analysisresult",
            constraint=models.UniqueConstraint(
                fields=("session", "analysis_type"),
                name="analytics_result_session_type_unique",
            ),
        ),
        migrations.AddIndex(
            model_name="analysisresult",
            index=models.Index(fields=["ifc_source", "analysis_type", "completed_at"], name="analytics_an_ifc_s_2a38da_idx"),
        ),
        migrations.AddIndex(
            model_name="analysisresult",
            index=models.Index(fields=["session", "status"], name="analytics_an_session_0bfc15_idx"),
        ),
        migrations.DeleteModel(name="AnalyticsRun"),
    ]
