# Generated by hand on 2026-04-20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("analytics", "0003_refactor_analytics_models"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="analysissession",
            name="report_json_path",
        ),
    ]
