# Generated by Django 5.2.8 on 2026-04-20 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0004_remove_analysissession_report_json_path"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="analysisresult",
            new_name="analytics_a_ifc_sou_9e0627_idx",
            old_name="analytics_an_ifc_s_2a38da_idx",
        ),
        migrations.RenameIndex(
            model_name="analysisresult",
            new_name="analytics_a_session_3d7f23_idx",
            old_name="analytics_an_session_0bfc15_idx",
        ),
        migrations.RenameIndex(
            model_name="analysissession",
            new_name="analytics_a_owner_i_06fe59_idx",
            old_name="analytics_an_owner_ba5614_idx",
        ),
        migrations.RenameIndex(
            model_name="analysissession",
            new_name="analytics_a_ifc_sou_3c4bec_idx",
            old_name="analytics_an_ifc_so_d710d0_idx",
        ),
        migrations.RenameIndex(
            model_name="analysissession",
            new_name="analytics_a_celery__a9bf80_idx",
            old_name="analytics_an_celery_07f297_idx",
        ),
        migrations.RenameIndex(
            model_name="ifcanalysisfile",
            new_name="analytics_i_owner_i_fddad2_idx",
            old_name="analytics_if_owner_09020f_idx",
        ),
        migrations.RenameIndex(
            model_name="ifcanalysisfile",
            new_name="analytics_i_created_d7daee_idx",
            old_name="analytics_if_created_652520_i",
        ),
    ]
